import { readFileSync, writeFileSync } from 'fs';

const a = "A reflexão musical e lírica proposta em music-o-preco-da-saudade apresenta uma estrutura inegavelmente curiosa: ao mesmo tempo que retrata uma devoção persistente pela figura de Beatriz Viterbo, incorpora a imagem e o escárnio direcionado ao primo falastrão Carlos Argentino Daneri como seu inseparável castigo melancólico. E é precisamente aqui que aplicamos nossa lente: existe na descrição de Carlos uma ironia mordaz, uma zombaria que beira a piada através da sua fútil obsessão intelectual. Mas, será que essa zombaria é o argumento da música? Não. A zombaria em relação a Carlos serve mais como um peso suportado pelo narrador — o pedágio imposto —, mas o verdadeiro argumento da canção reside na absurda e perfeitamente racional devoção doentia pela memória de Beatriz. Se removermos a crueldade intelectual das estrofes três e quatro, a melancolia dolorida do refrão e do violão caipira ainda sustenta a essência do post perfeitamente. O riso ou o sorriso irônico que as farpas ao primo despertam funciona mais como um preenchimento, uma moldura narrativa borgiana, mas não sustenta sozinha as vigas inteiras de emoção subjacentes. A canção é grave desde as notas em drop-D até a conclusão de aceitação fática e inútil daquele seu universo peculiar.";

const b = "Já na jornada em inglês pelo void de music-crystallizing-from-the-nothing, deparamo-nos com uma investigação existencial sobre os fundamentos da identidade fluida e temporal. O post aborda processos ontológicos e quânticos através de metáforas marítimas e conceituais de onda versus oceano, tudo isso ancorado num cenário ambiente. A pergunta que fazemos como Comedy-Carries-Argument Reader é contudo: há sequer alguma busca por riso estrutural aqui? Não. A gravidade de registro transborda no vocabulário adotado, assumindo abertamente o tom sério e metafísico, sem qualquer tentativa de aliviar o impacto existencial ou criar contraste rítmico humorístico que resguarde uma exposição maior do autor. O post mergulha corajosamente nas profundezas conceituais mas o faz sob uma armadura pesada de formalismo poético — proteções graves. A identidade é observada sob microscópios sérios do pensamento especulativo. Embora muito da especulação e das contradições sejam expostas de peito aberto (I contradict myself — I can), não experimentamos a fragilidade de apostar a força dessas convicções num meio leviano. Como leitor do registro, não podemos senão observar que o formato escolhido não utiliza alavancas cômicas — não há o que mentalmente remover que revele desmoronamentos do argumento por via de uma anedota ou observação cortante falhada. É um trabalho reflexivo puramente frontal e etéreo.";

const c = "Confrontando a melancólica jornada por ruas familiares e bibliotecas viciadas de music-o-preco-da-saudade com os vastos oceanos probatórios da identidade em music-crystallizing-from-the-nothing, a disputa sob essa perspectiva nos devolve duas faixas que lidam com a solenidade de forma particular. Ambas constroem sua narrativa essencialmente longe do puro uso estrutural do cômico ou do satírico, embora a primeira incorpore alguns laivos de sarcasmo no processo. Em music-o-preco-da-saudade, deparamo-nos com as descrições quase caricatas e amarguradas da futilidade literária de Daneri; no entanto, mesmo as farpas e ironias não carregam, em si, os alicerces fundamentais da música. Se as removermos ou as suavizarmos, o envelhecimento sombrio do narrador mantém o compasso e o peso da sua perda no violão melancólico sem ser derrubado. Em music-crystallizing-from-the-nothing o clima poético se propõe austero e puramente especulativo desde o alvorecer, explorando a existência e a ausência sob uma estética quase transcendental. Sob a ótica onde rir desmascara o sério enquanto sustentáculo da reflexão, music-o-preco-da-saudade pelo menos ousa tecer esse contraponto irônico às custas de Carlos Argentino, demonstrando uma forma sutil de expor um incômodo intelectual cínico — ainda que decorativo —, ganhando margem por sua leve irreverência comparativa contra um poético monolito sonoro.";

console.log('Words A:', a.split(/\s+/).length);
console.log('Words B:', b.split(/\s+/).length);
console.log('Words C:', c.split(/\s+/).length);
