export const lyrics = [
  "When I wake up in the morning",
  "There isn’t a “me” all at once",
  "There’s just some awareness",
  "Floating in an ill-defined space",
  "Then sensations gather",
  "Images form",
  "A thought appears — “Where am I?” “What time is it?”",
  "And a little later",
  "The whole psychosocial self",
  "Boots back online",
  "",
  "You can say it’s just the brain",
  "Shifting states in a body in a room",
  "Or you can say",
  "Reality is crystallizing",
  "Out of something like nothing",
  "I don’t feel the need to choose",
  "",
  "Maybe pattern is more basic than stuff",
  "Maybe the world is habits of perception",
  "Regularities we agreed to trust",
  "Not a solid stage beneath everything",
  "We build physics from patterns",
  "Then treat the patterns like stone",
  "But what if “stone” is just",
  "The most stable story we’ve told?",
  "",
  "Science is beautiful",
  "I spend my life inside it",
  "But I don’t feel",
  "That particles are the final ground",
  "The data we call “reality”",
  "Is a web of relations",
  "A history of observations",
  "Condensed into law",
  "You can do engineering",
  "Without assuming",
  "There’s an absolute thing",
  "Behind the equations",
  "",
  "First there is raw experience",
  "Then reaction",
  "Then relationship —",
  "And pattern lives in relationship",
  "Maybe “objective matter”",
  "Is just one very successful pattern",
  "In the mind",
  "",
  "Maybe pattern is more basic than stuff",
  "Maybe we are relations in motion",
  "Minds are knots in a larger weave",
  "Temporarily calling themselves “me”",
  "We rise like structure in noise",
  "Convincing ourselves we’re solid",
  "But under the form and the name",
  "It’s process, all the way down",
  "",
  "I don’t need one clean story",
  "I can hold contradictions",
  "The engineer and the mystic",
  "Sharing the same skull",
  "If there are things we don’t understand",
  "Psi, mind, strange phenomena",
  "Maybe it’s new physics",
  "Or physics that’s wider than we thought",
  "If there’s a probability you can write",
  "If there’s a model you can build",
  "Why say “not physics”?",
  "Why draw the border there?",
  "",
  "Maybe pattern is more basic than stuff",
  "Maybe the self is a recurring wave",
  "In a field that doesn’t belong",
  "To space and time alone",
  "We crystallize, we dissolve",
  "Stories the field tells locally",
  "And when the noise of the person gets quiet",
  "What’s left feels strangely kind",
  "Not proven",
  "Not a theorem",
  "Just what remains",
  "When the mind is still"
];
